### ISSUE TITLE
PHP 7.4 LTS

### ISSUE THREAD

**Issue by Danack** [Danack/RfcCodex#17]
**PHP 7.4 LTS**

It is quite likely that there will be a wish for PHP 7.4 support to happen for longer than the core PHP project wishes to maintain.

If some group could be found or formed, to do the work of maintaining PHP 7.4 separate to core PHP, there is enough time for a LTS version to be organised.

Anyone looking to take part in that work should feel free to leave their contact details here. I will also try to collate volunteer info from other sources e.g. PHP internals.

The aim is to make it possible for interested parties to find each other, rather than a personal desire to be involved in that work myself.

**Comment by sukrosono** [comment]
Well, I don't think I am qualified to be part of the maintainer team. It seems and more often I will break things instead of keeping it working. So please count me but under bold label learning. As for my country Indonesia :indonesia: , I am sure that we have many PHP users, hopefully, people will also interested to be involved in this.

![image](https://user-images.githubusercontent.com/3001652/82443069-0f108180-9acb-11ea-9042-85e78206b53f.png)
despite all the work, is it possible to give an arbitrary date if the LTS is formed?

**Comment by Danack** [comment]
Sorry, not really sure what you're asking.

Any LTS version would be separately maintained from the PHP core group, and the dates above are the support end times for the PHP group.

**Comment by Danack** [comment]
Closing, as not appropriate to document here, probably.
